export const nameBand = 'SAMUEL KING ';
export const nameSongs = [
	"KAI'S THEME", /*1*/
	"GOJO SATORU HOLLOW PURPLE THEME", /*2*/
	"SPIDER-VERSE THEME | EPIC MUSIC SUITE", /*3*/
	"ONE PIECE OST: OVERTAKEN", /*4*/
	"KAI'S THEME | EPIC VERSION", /*5*/
	"TENGEN VS GYUTARO FINAL FIGHT THEME", /*6*/
	"EVIL MORTY THEME", /*7*/
	"DEMON SLAYER: ZENITSU THEME", /*8*/
	"ATTACK ON TITAN: BEFORE LIGHTS OUT", /*9*/
	"THE BATMAN - MAIN TRAILER MUSIC", /*10*/
	"GIORNO'S THEME BUT IT'S EPIC VERSION", /*11*/
	"ATTACK ON TITAN S4: ASHES ON THE FIRE", /*12*/
	"HOUSE OF THE DRAGON: TARGARYEN THEME", /*13*/
	"ELDEN RING MAIN THEME", /*14*/
	"ONE PIECE: THE VERY VERY VERY STRONGEST", /*15*/
	"LEVI VS ZEKE THEME", /*16*/
	"HOIST THE COLOURS X HE'S A PIRATE", /*17*/
	"WARHAMMER TITAN THEME", /*18*/
	"KAI'S THEME & AGNI KAI", /*19*/
	"YOUSEEBIGGIRL/T:T", /*20*/
]