export default [
  "SCRIBBLE",
  "TWO MONTHS OFF",
  "REZ",
  "CUPS",
  "JUMBO",
  "SHUDDER",
  "DARK & LONG",
  "BORN SLIPPY .NUXX",
  "BELLS & CIRCLE",
  "GET YOUR SHIRT",
  "TRAPPED",
  "LOW BURN",
  "I EXHALE",
  "IF I RAH",
  "WHY WHY",
  "PEARL'S GIRL",
  "SOLA SISTIM",
  "KING OF SNAKE",
  "MOANER",
  "SPIKEE",
];