export const nameBand = 'HOUSE OF THE DRAGON';
export const nameSongs = [
	"TARGARYEN THEME - EPIC VERSION", /*1*/
	"LANNISTER THEME - EPIC VERSION", /*2*/
	"MAIN TITLE (FROM GAME OF THRONES)", /*3*/
	"END A WAR BEFORE IT BEGINS", /*4*/
	"FIGHT FOR OUR QUEEN", /*5*/
	"ALL MUST CHOOSE", /*6*/
	"THE HEIRS OF THE DRAGON", /*7*/
	"REIGN OF THE TARGARYENS", /*8*/
	"RHAENYRA’S WELCOME", /*9*/
	"A PACK OF HOUNDS", /*10*/
	"THE PRINCE THAT WAS PROMISED", /*11*/
	"SURRENDER", /*12*/
	"LAMENT", /*13*/
	"FATE OF THE KINGDOMS", /*14*/
	"INTERESTS OF THE REALM", /*15*/
	"THE PROMISE", /*16*/
	"WINTERFELL", /*17*/
	"THE RAINS OF CASTAMERE", /*18*/
	"DRAGONSTONE", /*19*/
	"BLOOD OF THE DRAGON", /*20*/
]